### PR TITLE
Create languages/he/harmony.json file

### PR DESCRIPTION
**Pull request by ShlomoCode**

### CODE REVIEW

**Comment by barisusakli** [comment]
@ShlomoCode done, thanks for the translations

**Comment by barisusakli** [comment]
@ShlomoCode  we are moving the language files to core so you can translate it on transifex. see this issue https://github.com/NodeBB/NodeBB/issues/11584

**Comment by ShlomoCode** [comment]
> @ShlomoCode we are moving the language files to core so you can translate it on transifex. see this issue [NodeBB/NodeBB#11584](https://github.com/NodeBB/NodeBB/issues/11584)

Does this mean that I will have to re-translate in Transifex or that what I translated here on GitHub will be copied to Transifex?

**Comment by barisusakli** [comment]
You will have to redo on transifex, but you can just copy your stuff from here to transifex once the files are available there.

**Pull request merged**
